title: Dude
author: Aditya Wardana
email: wardanaaditya49@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I believe my life is blessed

# social links
twitter_username: aditya # DO NOT include the @ character, or else the build will fail!
github_username:  aditwar # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
