title: Support Me Plz
author: Aditya Wardana
email: wardanaaditya49@gmail.com
theme: minima 
description: > # this means to ignore newlines until "baseurl:"
  I hope my life is blessed to everyone

# social links
twitter_username: aditya # DO NOT include the @ character, or else the build will fail!
github_username:  aditwar # DO NOT include the @ character, or else the build will fail!

show_excerpts: flase # set to false to remove excerpts on the homepage
